-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 01:59:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simple_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simple_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple_company` ;
USE `simple_company` ;

-- -----------------------------------------------------
-- Table `simple_company`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`product` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(45) NOT NULL,
  `prod_desc` VARCHAR(1024) NOT NULL,
  `prod_category` INT NOT NULL,
  `prod_upc` CHAR(12) NOT NULL,
  `prod_count` INT NOT NULL,
  `prod_image` VARCHAR(256) NOT NULL,
  `prod_price` DECIMAL(5,2) NOT NULL,
  `production_status` TINYINT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`user` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email_verified` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`credit_card` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`credit_card` (
  `cc_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cc_number` VARCHAR(45) NOT NULL,
  `exp_date` VARCHAR(45) NOT NULL,
  `security_code` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `CUSTOMER_id_fk_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`cc_id`),
  CONSTRAINT `fk_CUSTOMER_id_`
    FOREIGN KEY (`user_id`)
    REFERENCES `simple_company`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`order` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` TIMESTAMP NOT NULL,
  `order_amt` DECIMAL(9,2) NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `cc_id` INT NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `PRODUCT_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `CUSTOMER_id_fk` (`user_id` ASC) VISIBLE,
  INDEX `CC_id_fk_idx` (`cc_id` ASC) VISIBLE,
  CONSTRAINT `PRODUCT_id_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `simple_company`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CUSTOMER_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `simple_company`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CC_id_fk`
    FOREIGN KEY (`cc_id`)
    REFERENCES `simple_company`.`credit_card` (`cc_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`address` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `CUSTOMER_id_fk_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `CUSTOMER_id_fk_`
    FOREIGN KEY (`user_id`)
    REFERENCES `simple_company`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`roles` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`user_roles` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `userid_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `simple_company`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `simple_company`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple_company`.`cart_items` ;

CREATE TABLE IF NOT EXISTS `simple_company`.`cart_items` (
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `count` INT NOT NULL,
  INDEX `idproduct_idx` (`product_id` ASC) VISIBLE,
  INDEX `iduser_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `product_id`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`user_id`)
    REFERENCES `simple_company`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idproduct`
    FOREIGN KEY (`product_id`)
    REFERENCES `simple_company`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
